### PR TITLE
Validate results of Preapply and propagate errors

### LINKED ISSUE #45: Clean up pre-apply operation
This result is just discarded, which results in an extra network request on forged operations. 

Should be safe to remove once proper regression tests are in place.

### PR DESCRIPTION
**Pull request by keefertaylor**
Wire associated integration and unit tests.

Fixes #45

### CODE REVIEW

File: TezosKit/Client/TezosNodeClient.swift [hunk 1]
```diff
@@ -603,12 +607,50 @@ public class TezosNodeClient: AbstractClient {
...
-  /**
-   * Retrieve metadata needed to forge / pre-apply / sign / inject an operation.
-   *
-   * This method parallelizes fetches to get chain and address data and returns all required data
-   * together as an OperationData object.
-   */
+  /// Parse a preapplication RPC response and extract an error if one occurred.
+  internal static func preapplicationError(from preapplicationResponse: [[String: Any]]) -> TezosKitError? {
+    let contents: [[String: Any]] = preapplicationResponse.compactMap { operation in
+     operation["contents"] as? [[String: Any]]
```
Comment (jlaws) [inline TezosKit/Client/TezosNodeClient.swift]: Update "contents", "metadata", etc... to be constants declared, and commented, somewhere?
